import re

TOKEN_RE = re.compile(
    r"[^a-z0-9à-ÿ]+"
)
# DEFAULT_SELECTOR removido: o index_script.js detecta os elementos sozinho.


# ---------------------------------------------------------------------------
# Sinônimos PT -> EN (ações, e-commerce, navegação, formulários, conta, social)
# ---------------------------------------------------------------------------
SYNONYMS = {
    # elementos / UI genérica
    "botão": "button",
    "botao": "button",
    "botoes": "button",
    "botões": "button",
    "link": "link",
    "ligação": "link",
    "campo": "field",
    "caixa": "box",
    "menu": "menu",
    "aba": "tab",
    "abas": "tab",
    "guia": "tab",
    "janela": "window",
    "janela modal": "modal",
    "popup": "popup",
    "pop-up": "popup",
    "aviso": "alert",
    "alerta": "alert",
    "notificação": "notification",
    "notificacao": "notification",
    "cartão": "card",
    "cartao": "card",
    "rótulo": "label",
    "rotulo": "label",
    "etiqueta": "tag",
    "selo": "badge",
    "ícone": "icon",
    "icone": "icon",
    "imagem": "image",
    "foto": "photo",
    "avatar": "avatar",
    "barra": "bar",
    "barra lateral": "sidebar",
    "cabeçalho": "header",
    "cabecalho": "header",
    "rodapé": "footer",
    "rodape": "footer",
    "gaveta": "drawer",
    "painel": "panel",
    "acordeão": "accordion",
    "acordeon": "accordion",
    "carrossel": "carousel",
    "slide": "slide",
    "controle deslizante": "slider",
    "dica": "tooltip",
    "trilha": "breadcrumb",
    "paginação": "pagination",
    "paginacao": "pagination",
    "tabela": "table",
    "linha": "row",
    "coluna": "column",
    "célula": "cell",
    "celula": "cell",
    "lista": "list",
    "item": "item",
    "formulário": "form",
    "formulario": "form",
    "caixa de texto": "textbox",
    "caixa de seleção": "checkbox",
    "caixa de selecao": "checkbox",
    "caixa de seleção múltipla": "checkbox",
    "seletor": "select",
    "menu suspenso": "dropdown",
    "lista suspensa": "dropdown",
    "combo": "combobox",
    "controle deslizante de valor": "range",
    "interruptor": "toggle",
    "alternador": "switch",
    "controle": "control",
    "widget": "widget",
    "componente": "component",

    # ações principais
    "adicionar": "add",
    "adicione": "add",
    "incluir": "add",
    "inclua": "add",
    "remover": "remove",
    "remova": "remove",
    "excluir": "delete",
    "exclua": "delete",
    "apagar": "delete",
    "deletar": "delete",
    "editar": "edit",
    "edite": "edit",
    "modificar": "edit",
    "alterar": "edit",
    "atualizar": "update",
    "atualize": "update",
    "clicar": "click",
    "clique": "click",
    "toque": "tap",
    "tocar": "tap",
    "pressionar": "press",
    "pressione": "press",
    "selecionar": "select",
    "selecione": "select",
    "escolher": "choose",
    "escolha": "choose",
    "marcar": "check",
    "marque": "check",
    "desmarcar": "uncheck",
    "desmarque": "uncheck",
    "alternar": "toggle",
    "expandir": "expand",
    "expanda": "expand",
    "recolher": "collapse",
    "colapsar": "collapse",
    "arrastar": "drag",
    "soltar": "drop",
    "rolar": "scroll",
    "deslizar": "swipe",
    "ampliar": "zoom",
    "aumentar": "increase",
    "diminuir": "decrease",
    "reduzir": "decrease",

    # navegação / fluxo
    "buscar": "search",
    "pesquisar": "search",
    "pesquise": "search",
    "procurar": "search",
    "filtrar": "filter",
    "filtre": "filter",
    "ordenar": "sort",
    "ordene": "sort",
    "classificar": "sort",
    "continuar": "continue",
    "continue": "continue",
    "prosseguir": "continue",
    "voltar": "back",
    "volte": "back",
    "próximo": "next",
    "proximo": "next",
    "próxima": "next",
    "proxima": "next",
    "anterior": "previous",
    "início": "home",
    "inicio": "home",
    "página inicial": "home",
    "pagina inicial": "home",
    "abrir": "open",
    "abra": "open",
    "fechar": "close",
    "feche": "close",
    "sair": "logout",
    "entrar": "login",
    "acessar": "login",
    "cadastrar": "signup",
    "cadastre-se": "signup",
    "registrar": "register",
    "inscrever-se": "subscribe",
    "assinar": "subscribe",
    "cancelar assinatura": "unsubscribe",
    "carregar mais": "load more",
    "ver mais": "view more",
    "mostrar mais": "show more",
    "mostrar menos": "show less",
    "limpar": "clear",
    "limpe": "clear",
    "redefinir": "reset",
    "resetar": "reset",

    # formulários / conta
    "enviar": "send",
    "envie": "send",
    "submeter": "submit",
    "confirmar": "confirm",
    "confirme": "confirm",
    "cancelar": "cancel",
    "salvar": "save",
    "salve": "save",
    "gravar": "save",
    "senha": "password",
    "usuário": "username",
    "usuario": "username",
    "e-mail": "email",
    "email": "email",
    "nome": "name",
    "sobrenome": "last name",
    "endereço": "address",
    "endereco": "address",
    "telefone": "phone",
    "celular": "phone",
    "esqueci a senha": "forgot password",
    "lembrar de mim": "remember me",
    "verificar": "verify",
    "validar": "validate",
    "perfil": "profile",
    "conta": "account",
    "configurações": "settings",
    "configuracoes": "settings",
    "preferências": "preferences",
    "preferencias": "preferences",

    # e-commerce
    "comprar": "buy",
    "compre": "buy",
    "adquirir": "purchase",
    "carrinho": "cart",
    "sacola": "bag",
    "finalizar compra": "checkout",
    "pagar": "pay",
    "pagamento": "payment",
    "preço": "price",
    "preco": "price",
    "desconto": "discount",
    "cupom": "coupon",
    "frete": "shipping",
    "entrega": "delivery",
    "produto": "product",
    "estoque": "stock",
    "quantidade": "quantity",
    "avaliar": "rate",
    "avaliação": "review",
    "avaliacao": "review",
    "comentar": "comment",
    "comentário": "comment",
    "comentario": "comment",
    "favoritar": "favorite",
    "favoritos": "favorites",
    "lista de desejos": "wishlist",
    "cupom de desconto": "coupon",
    "pedido": "order",
    "rastrear pedido": "track order",
    "devolução": "return",
    "devolucao": "return",
    "reembolso": "refund",

    # social / mídia
    "curtir": "like",
    "curta": "like",
    "seguir": "follow",
    "siga": "follow",
    "deixar de seguir": "unfollow",
    "compartilhar": "share",
    "compartilhe": "share",
    "responder": "reply",
    "publicar": "post",
    "postar": "post",
    "denunciar": "report",
    "bloquear": "block",
    "silenciar": "mute",
    "mensagem": "message",
    "chat": "chat",
    "notificações": "notifications",
    "notificacoes": "notifications",

    # arquivos / mídia
    "carregar": "upload",
    "fazer upload": "upload",
    "baixar": "download",
    "anexar": "attach",
    "anexo": "attachment",
    "arquivo": "file",
    "documento": "document",

    # produtos de exemplo (mantidos do original)
    "mochila": "backpack",
    "bicicleta": "bike",
    "luz": "light",
    "camisa": "shirt",
    "jaqueta": "jacket",
    "macacão": "onesie",
    "macacao": "onesie",
}


ACTION_WORDS = {
    "add", "remove", "delete", "buy", "purchase", "submit", "save",
    "cancel", "confirm", "open", "close", "select", "choose", "click",
    "tap", "press", "edit", "update", "search", "login", "logout",
    "signup", "register", "subscribe", "unsubscribe", "upload", "download",
    "send", "apply", "filter", "sort", "checkout", "increase", "decrease",
    "view", "continue", "next", "previous", "back", "clear", "reset",
    "check", "uncheck", "toggle", "expand", "collapse", "drag", "drop",
    "scroll", "swipe", "zoom", "share", "like", "follow", "unfollow",
    "report", "block", "mute", "comment", "reply", "rate", "review",
    "pay", "track", "return", "refund", "verify", "validate", "attach",
    "load more", "view more", "show more", "show less",
}


STOPWORDS = {
    "a", "o", "as", "os",
    "um", "uma", "uns", "umas",
    "de", "do", "da", "dos", "das",
    "em", "no", "na", "nos", "nas",
    "para", "por", "com", "sem",
    "ao", "aos", "à", "às",
    "e", "ou", "que", "se",
    "eu", "tu", "ele", "ela", "nós", "nos", "vocês", "voces", "eles", "elas",
    "meu", "minha", "meus", "minhas",
    "seu", "sua", "seus", "suas",
    "este", "esta", "isto", "esse", "essa", "isso", "aquele", "aquela", "aquilo",
    "é", "são", "está", "estão",
    "the", "a", "an", "of", "to", "in", "on", "for", "with",
}


STRUCTURAL_WORDS = {
    "button", "link", "input", "textbox", "field", "element", "elemento",
    "menu", "navbar", "nav", "header", "footer", "sidebar", "aside",
    "modal", "dialog", "popup", "overlay", "drawer", "panel",
    "dropdown", "select", "combobox", "checkbox", "radio", "switch", "toggle",
    "accordion", "carousel", "slider", "tab", "tabpanel", "tooltip",
    "badge", "avatar", "breadcrumb", "pagination", "card", "chip", "tag",
    "banner", "alert", "notification", "toast",
    "form", "fieldset", "legend",
    "table", "row", "column", "cell",
    "list", "item", "icon", "image", "video", "audio",
    "widget", "component", "section", "article",
}



 
# ---------------------------------------------------------------------------
# Pesos de scoring
# ---------------------------------------------------------------------------
ACTION_CONTENT_BONUS = 0.30
ACTION_MISMATCH_DAMPING = 0.55
 
OBJECT_CONTEXT_BONUS = 0.30
OBJECT_MISMATCH_DAMPING = 0.70
 
EXTRACT_TEXT_BONUS = 0.15
 
 
ACTION_ROLE_WEIGHTS = {
    "click": {
        "button": 0.15,
        "link": 0.12,
        "checkbox": 0.10,
        "radio": 0.10,
        "combobox": 0.08,
        "tab": 0.10,
        "menuitem": 0.10,
        "switch": 0.10,
        "clickable": 0.05,   # div/span com cursor:pointer (detectado pelo script)
        "div": -0.05,
        "span": -0.05,
        "p": -0.05,
    },
    "fill": {
        "textbox": 0.15,
        "input": 0.15,
        "textarea": 0.15,
        "combobox": 0.10,
        "spinbutton": 0.10,
        "button": -0.10,
        "link": -0.10,
    },
    "select": {
        "option": 0.15,
        "combobox": 0.12,
        "listbox": 0.10,
        "radio": 0.10,
        "checkbox": 0.08,
        "menuitem": 0.08,
        "button": -0.05,
    },
    "check": {
        "checkbox": 0.15,
        "switch": 0.12,
        "radio": 0.08,
    },
    "toggle": {
        "switch": 0.15,
        "checkbox": 0.12,
        "button": 0.05,
    },
    "search": {
        "textbox": 0.15,
        "input": 0.15,
        "combobox": 0.08,
    },
    "filter": {
        "combobox": 0.12,
        "checkbox": 0.10,
        "button": 0.08,
        "listbox": 0.08,
    },
    "sort": {
        "button": 0.10,
        "combobox": 0.10,
        "link": 0.05,
    },
    "expand": {
        "button": 0.12,
        "summary": 0.12,
        "tab": 0.05,
    },
    "collapse": {
        "button": 0.12,
        "summary": 0.12,
    },
    "drag": {
        "slider": 0.15,
        "button": -0.05,
    },
    "scroll": {
        "scrollbar": 0.10,
    },
    "extract": {
        "button": 0.0,
        "link": 0.0,
    },
}